# path.yaml
path:
  - point:
      x: 0.0
      y: 0.0
      z: 0.0
    velocity:
      linear_x: 0.5
  - point:
      x: 1.0
      y: 0.5
      z: 0.0
    velocity:
      linear_x: 1.0
  - point:
      x: 2.0
      y: 1.0
      z: 0.0
    velocity:
      linear_x: 0.8
  - point:
      x: 3.0
      y: 1.5
      z: 0.0
    velocity:
      linear_x: 1.2
